<?php

namespace ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRatingRepository extends EntityRepository
{
}
